algoritmo "sucessor e antecessor"
var
   altura, largura, area, litros : real

inicio
      Escreva ("Qual a largura da parede?")
      Leia (largura)
      Escreva ("Qual a altura da parede?")
      Leia (altura)
      area <- (largura*altura)
      Escreval ("A parede então possui ", area, " metros quadrados")
      litros <- (area/2)
      Escreva ("Logo, você precisará de ", litros, " litros de tinta")



      

fimalgoritmo